language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - MODULES="Django>=1.4,<1.5"
  - MODULES="Django>=1.5,<1.6"
  - MODULES="Django>=1.6,<1.7"
  - MODULES="Django>=1.7,<1.8"
matrix:
  exclude:
    - python: "2.6"
      env: MODULES="Django>=1.7,<1.8"
    - python: "3.3"
      env: MODULES="Django>=1.4,<1.5"
    - python: "3.4"
      env: MODULES="Django>=1.4,<1.5"
install:
  - pip install $MODULES
  - pip install -e .
script:
  - python runtests.py
